-- =============================================================================
-- DataQuery Solutions — Datos iniciales del catálogo
-- Usa INSERT IGNORE para ser idempotente (seguro re-ejecutar en reinicios)
-- TRUNCATE al inicio garantiza datos frescos en cada arranque
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE statement_keyword;
TRUNCATE TABLE statement_syntax;
TRUNCATE TABLE data_type_mapping;
TRUNCATE TABLE keyword;
TRUNCATE TABLE data_type;
TRUNCATE TABLE sql_statement;
TRUNCATE TABLE dialect;
SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- SECCIÓN 1: DIALECTOS
-- =============================================================================
INSERT IGNORE INTO dialect (name, display_name, default_port, brand_color, driver_class, supports_txn, jdbc_url_pattern, since_version, notes) VALUES
('MYSQL',      'MySQL 8.x',        3306,  '#4479A1', 'com.mysql.cj.jdbc.Driver',                     1, 'jdbc:mysql://{host}:{port}/{db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true', '5.0',  'Motor relacional más usado en la web'),
('POSTGRESQL', 'PostgreSQL 15+',   5432,  '#336791', 'org.postgresql.Driver',                        1, 'jdbc:postgresql://{host}:{port}/{db}?sslmode=disable',             '9.0',  'Motor objeto-relacional, muy completo en estándares SQL'),
('SQLSERVER',  'SQL Server 2019+', 1433,  '#CC2927', 'com.microsoft.sqlserver.jdbc.SQLServerDriver',  1, 'jdbc:sqlserver://{host}:{port};databaseName={db};encrypt=false',   '2008', 'Motor empresarial de Microsoft'),
('MONGODB',    'MongoDB 6+',       27017, '#47A248', '',                                             0, 'mongodb://{host}:{port}/{db}',                                     '4.0',  'Motor NoSQL orientado a documentos');

-- =============================================================================
-- SECCIÓN 2: TIPOS DE SENTENCIA SQL
-- =============================================================================
INSERT IGNORE INTO sql_statement (name, category, description) VALUES
('SELECT',       'DML', 'Consulta y recuperación de datos'),
('INSERT',       'DML', 'Inserción de nuevas filas'),
('UPDATE',       'DML', 'Modificación de filas existentes'),
('DELETE',       'DML', 'Eliminación de filas'),
('CREATE_TABLE', 'DDL', 'Creación de una tabla nueva'),
('ALTER_TABLE',  'DDL', 'Modificación de estructura de tabla'),
('DROP_TABLE',   'DDL', 'Eliminación de tabla'),
('CREATE_INDEX', 'DDL', 'Creación de índice sobre una tabla'),
('TRUNCATE',     'DDL', 'Vaciado rápido de tabla'),
('BEGIN',        'TCL', 'Inicio de transacción explícita'),
('COMMIT',       'TCL', 'Confirmación de transacción'),
('ROLLBACK',     'TCL', 'Reversión de transacción'),
('GRANT',        'DCL', 'Otorgar permisos a usuario'),
('REVOKE',       'DCL', 'Revocar permisos de usuario');

-- =============================================================================
-- SECCIÓN 3: TIPOS DE DATO ABSTRACTOS
-- =============================================================================
INSERT IGNORE INTO data_type (name, description) VALUES
('INT',      'Número entero'),
('FLOAT',    'Número decimal / punto flotante'),
('VARCHAR',  'Cadena de texto de longitud variable'),
('TEXT',     'Texto largo sin límite definido'),
('BOOLEAN',  'Valor lógico verdadero/falso'),
('DATETIME', 'Fecha y hora'),
('DATE',     'Solo fecha'),
('TIME',     'Solo hora'),
('BLOB',     'Datos binarios'),
('JSON',     'Documento JSON'),
('UUID',     'Identificador único universal'),
('ARRAY',    'Arreglo de valores (PostgreSQL nativo)'),
('UNKNOWN',  'Tipo no mapeado o desconocido');

-- =============================================================================
-- SECCIÓN 4: KEYWORDS — MYSQL (dialect_id=1)
-- Nota: cada (dialect_id, word) debe ser único por constraint uq_dialect_word
-- =============================================================================
INSERT IGNORE INTO keyword (dialect_id, word, token_type, category, is_reserved, since_version, notes) VALUES
-- DML base
(1,'SELECT','RESERVED','DML',1,'3.0',NULL),
(1,'INSERT','RESERVED','DML',1,'3.0',NULL),
(1,'UPDATE','RESERVED','DML',1,'3.0',NULL),
(1,'DELETE','RESERVED','DML',1,'3.0',NULL),
(1,'FROM','CLAUSE','DML',1,'3.0',NULL),
(1,'WHERE','CLAUSE','DML',1,'3.0',NULL),
(1,'SET','CLAUSE','DML',1,'3.0',NULL),
(1,'INTO','CLAUSE','DML',1,'3.0',NULL),
(1,'VALUES','CLAUSE','DML',1,'3.0',NULL),
-- DDL base
(1,'CREATE','RESERVED','DDL',1,'3.0',NULL),
(1,'TABLE','RESERVED','DDL',1,'3.0',NULL),
(1,'DROP','RESERVED','DDL',1,'3.0',NULL),
(1,'ALTER','RESERVED','DDL',1,'3.0',NULL),
(1,'ADD','CLAUSE','DDL',1,'3.0',NULL),
(1,'COLUMN','CLAUSE','DDL',1,'3.0',NULL),
(1,'INDEX','RESERVED','DDL',1,'3.0',NULL),
(1,'PRIMARY','RESERVED','DDL',1,'3.0',NULL),
(1,'KEY','RESERVED','DDL',1,'3.0',NULL),
(1,'FOREIGN','RESERVED','DDL',1,'3.0',NULL),
(1,'REFERENCES','RESERVED','DDL',1,'3.0',NULL),
(1,'UNIQUE','RESERVED','DDL',1,'3.0',NULL),
(1,'DEFAULT','CLAUSE','DDL',1,'3.0',NULL),
(1,'NOT','OPERATOR','DML',1,'3.0',NULL),
(1,'NULL','RESERVED','DML',1,'3.0',NULL),
(1,'CONSTRAINT','RESERVED','DDL',1,'3.0',NULL),
(1,'AUTO_INCREMENT','MODIFIER','DDL',0,'3.0','Equivalente a SERIAL en PostgreSQL'),
(1,'TRUNCATE','RESERVED','DDL',1,'3.0',NULL),
(1,'IF','MODIFIER','DDL',1,'3.0',NULL),
(1,'EXISTS','MODIFIER','DDL',1,'3.0',NULL),
(1,'ENGINE','PRAGMA','DDL',0,'3.0','Ej: ENGINE=InnoDB'),
(1,'CHARSET','PRAGMA','DDL',0,'3.0','Ej: DEFAULT CHARSET=utf8mb4'),
(1,'COLLATE','PRAGMA','DDL',0,'3.0',NULL),
-- Joins
(1,'JOIN','CLAUSE','DML',1,'3.0',NULL),
(1,'INNER','MODIFIER','DML',0,'3.0',NULL),
(1,'LEFT','MODIFIER','DML',0,'3.0',NULL),
(1,'RIGHT','MODIFIER','DML',0,'3.0',NULL),
(1,'OUTER','MODIFIER','DML',0,'3.0',NULL),
(1,'CROSS','MODIFIER','DML',0,'3.0',NULL),
(1,'ON','CLAUSE','DML',1,'3.0',NULL),
(1,'AS','MODIFIER','DML',0,'3.0',NULL),
-- Cláusulas
(1,'ORDER','CLAUSE','DML',1,'3.0',NULL),
(1,'BY','CLAUSE','DML',1,'3.0',NULL),
(1,'GROUP','CLAUSE','DML',1,'3.0',NULL),
(1,'HAVING','CLAUSE','DML',1,'3.0',NULL),
(1,'DISTINCT','MODIFIER','DML',1,'3.0',NULL),
(1,'LIMIT','CLAUSE','DML',0,'3.0','Exclusivo MySQL/MariaDB para paginación'),
(1,'OFFSET','CLAUSE','DML',0,'3.0',NULL),
-- Operadores lógicos
(1,'AND','OPERATOR','DML',1,'3.0',NULL),
(1,'OR','OPERATOR','DML',1,'3.0',NULL),
(1,'IN','OPERATOR','DML',1,'3.0',NULL),
(1,'NOT IN','OPERATOR','DML',1,'3.0',NULL),
(1,'LIKE','OPERATOR','DML',1,'3.0',NULL),
(1,'NOT LIKE','OPERATOR','DML',1,'3.0',NULL),
(1,'BETWEEN','OPERATOR','DML',1,'3.0',NULL),
(1,'IS','OPERATOR','DML',1,'3.0',NULL),
(1,'IS NOT','OPERATOR','DML',1,'3.0',NULL),
(1,'CASE','RESERVED','DML',1,'3.0',NULL),
(1,'WHEN','CLAUSE','DML',1,'3.0',NULL),
(1,'THEN','CLAUSE','DML',1,'3.0',NULL),
(1,'ELSE','CLAUSE','DML',1,'3.0',NULL),
(1,'END','CLAUSE','DML',1,'3.0',NULL),
-- Funciones de agregado
(1,'COUNT','FUNCTION','AGGREGATE',0,'3.0',NULL),
(1,'SUM','FUNCTION','AGGREGATE',0,'3.0',NULL),
(1,'AVG','FUNCTION','AGGREGATE',0,'3.0',NULL),
(1,'MIN','FUNCTION','AGGREGATE',0,'3.0',NULL),
(1,'MAX','FUNCTION','AGGREGATE',0,'3.0',NULL),
(1,'GROUP_CONCAT','FUNCTION','AGGREGATE',0,'4.0','Exclusivo MySQL, equivalente a STRING_AGG'),
-- Funciones de fecha
(1,'NOW','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'CURDATE','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'CURTIME','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'DATE_FORMAT','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'DATEDIFF','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'DATE_ADD','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'YEAR','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'MONTH','FUNCTION','DATETIME',0,'3.0',NULL),
(1,'DAY','FUNCTION','DATETIME',0,'3.0',NULL),
-- Funciones de string
(1,'CONCAT','FUNCTION','STRING',0,'3.0',NULL),
(1,'LENGTH','FUNCTION','STRING',0,'3.0',NULL),
(1,'SUBSTRING','FUNCTION','STRING',0,'3.0',NULL),
(1,'UPPER','FUNCTION','STRING',0,'3.0',NULL),
(1,'LOWER','FUNCTION','STRING',0,'3.0',NULL),
(1,'TRIM','FUNCTION','STRING',0,'3.0',NULL),
(1,'REPLACE','FUNCTION','STRING',0,'4.0',NULL),
(1,'IFNULL','FUNCTION','DML',0,'3.0','Equivalente a COALESCE'),
(1,'COALESCE','FUNCTION','DML',0,'3.0',NULL),
-- JSON (MySQL 5.7+)
(1,'JSON_EXTRACT','FUNCTION','JSON',0,'5.7',NULL),
(1,'JSON_OBJECT','FUNCTION','JSON',0,'5.7',NULL),
(1,'JSON_ARRAY','FUNCTION','JSON',0,'5.7',NULL),
(1,'JSON_CONTAINS','FUNCTION','JSON',0,'5.7',NULL),
-- Window functions (MySQL 8.0+)
(1,'ROW_NUMBER','FUNCTION','WINDOW',0,'8.0',NULL),
(1,'RANK','FUNCTION','WINDOW',0,'8.0',NULL),
(1,'DENSE_RANK','FUNCTION','WINDOW',0,'8.0',NULL),
(1,'OVER','CLAUSE','WINDOW',0,'8.0',NULL),
(1,'PARTITION','CLAUSE','WINDOW',0,'8.0',NULL),
(1,'ROWS','CLAUSE','WINDOW',0,'8.0',NULL),
-- Pragmas / opciones MySQL
(1,'SHOW','RESERVED','DDL',0,'3.0',NULL),
(1,'DESCRIBE','RESERVED','DDL',0,'3.0',NULL),
(1,'EXPLAIN','RESERVED','DML',0,'3.0',NULL),
(1,'USE','RESERVED','DDL',0,'3.0',NULL),
(1,'STRAIGHT_JOIN','PRAGMA','DML',0,'3.0','Fuerza el orden de join'),
(1,'SQL_CALC_FOUND_ROWS','PRAGMA','DML',0,'4.0','Calcular total sin LIMIT'),
(1,'UNSIGNED','MODIFIER','DDL',0,'3.0',NULL),
(1,'ZEROFILL','MODIFIER','DDL',0,'3.0',NULL),
(1,'ENUM','DATA_TYPE','DDL',0,'3.0',NULL),
-- TCL
(1,'BEGIN','RESERVED','TCL',1,'3.0',NULL),
(1,'COMMIT','RESERVED','TCL',1,'3.0',NULL),
(1,'ROLLBACK','RESERVED','TCL',1,'3.0',NULL),
(1,'SAVEPOINT','RESERVED','TCL',1,'3.0',NULL),
(1,'START','RESERVED','TCL',1,'3.0','START TRANSACTION'),
(1,'TRANSACTION','RESERVED','TCL',1,'3.0',NULL);

-- =============================================================================
-- SECCIÓN 4: KEYWORDS — POSTGRESQL (dialect_id=2)
-- =============================================================================
INSERT IGNORE INTO keyword (dialect_id, word, token_type, category, is_reserved, since_version, notes) VALUES
(2,'SELECT','RESERVED','DML',1,'7.0',NULL),
(2,'INSERT','RESERVED','DML',1,'7.0',NULL),
(2,'UPDATE','RESERVED','DML',1,'7.0',NULL),
(2,'DELETE','RESERVED','DML',1,'7.0',NULL),
(2,'FROM','CLAUSE','DML',1,'7.0',NULL),
(2,'WHERE','CLAUSE','DML',1,'7.0',NULL),
(2,'SET','CLAUSE','DML',1,'7.0',NULL),
(2,'INTO','CLAUSE','DML',1,'7.0',NULL),
(2,'VALUES','CLAUSE','DML',1,'7.0',NULL),
(2,'CREATE','RESERVED','DDL',1,'7.0',NULL),
(2,'TABLE','RESERVED','DDL',1,'7.0',NULL),
(2,'DROP','RESERVED','DDL',1,'7.0',NULL),
(2,'ALTER','RESERVED','DDL',1,'7.0',NULL),
(2,'ADD','CLAUSE','DDL',1,'7.0',NULL),
(2,'COLUMN','CLAUSE','DDL',1,'7.0',NULL),
(2,'INDEX','RESERVED','DDL',1,'7.0',NULL),
(2,'PRIMARY','RESERVED','DDL',1,'7.0',NULL),
(2,'KEY','RESERVED','DDL',1,'7.0',NULL),
(2,'FOREIGN','RESERVED','DDL',1,'7.0',NULL),
(2,'REFERENCES','RESERVED','DDL',1,'7.0',NULL),
(2,'UNIQUE','RESERVED','DDL',1,'7.0',NULL),
(2,'DEFAULT','CLAUSE','DDL',1,'7.0',NULL),
(2,'NOT','OPERATOR','DML',1,'7.0',NULL),
(2,'NULL','RESERVED','DML',1,'7.0',NULL),
(2,'CONSTRAINT','RESERVED','DDL',1,'7.0',NULL),
(2,'TRUNCATE','RESERVED','DDL',1,'7.0',NULL),
(2,'IF','MODIFIER','DDL',1,'9.0',NULL),
(2,'EXISTS','MODIFIER','DDL',1,'7.0',NULL),
-- Exclusivos PostgreSQL
(2,'RETURNING','CLAUSE','DML',0,'8.2','Devuelve filas afectadas por INSERT/UPDATE/DELETE'),
(2,'ILIKE','OPERATOR','DML',0,'7.0','LIKE case-insensitive'),
(2,'LATERAL','MODIFIER','DML',0,'9.3','Referencia a columnas de tablas anteriores en FROM'),
(2,'EXCEPT','CLAUSE','DML',1,'7.0',NULL),
(2,'INTERSECT','CLAUSE','DML',1,'7.0',NULL),
(2,'FETCH','CLAUSE','DML',1,'8.4','Alternativa estándar SQL a LIMIT'),
(2,'NEXT','CLAUSE','DML',0,'8.4','FETCH NEXT n ROWS ONLY'),
(2,'ONLY','MODIFIER','DML',0,'8.4',NULL),
(2,'NULLS','MODIFIER','DML',0,'8.3','ORDER BY col NULLS FIRST/LAST'),
(2,'FIRST','MODIFIER','DML',0,'7.0',NULL),
(2,'LAST','MODIFIER','DML',0,'7.0',NULL),
(2,'FILTER','CLAUSE','AGGREGATE',0,'9.4','COUNT(*) FILTER (WHERE cond)'),
(2,'ON CONFLICT','CLAUSE','DML',0,'9.5','Upsert nativo'),
(2,'DO','CLAUSE','DML',0,'9.5',NULL),
(2,'NOTHING','CLAUSE','DML',0,'9.5','ON CONFLICT DO NOTHING'),
-- Tipos exclusivos PostgreSQL
(2,'SERIAL','DATA_TYPE','DDL',0,'7.0','Entero auto-incrementable (legacy)'),
(2,'BIGSERIAL','DATA_TYPE','DDL',0,'7.0',NULL),
(2,'SMALLSERIAL','DATA_TYPE','DDL',0,'7.0',NULL),
(2,'JSONB','DATA_TYPE','DDL',0,'9.4','JSON binario indexable'),
(2,'UUID','DATA_TYPE','DDL',0,'8.3',NULL),
(2,'ARRAY','DATA_TYPE','DDL',0,'7.0',NULL),
(2,'BYTEA','DATA_TYPE','DDL',0,'7.0','Datos binarios'),
(2,'CIDR','DATA_TYPE','DDL',0,'7.0','Dirección de red'),
(2,'INET','DATA_TYPE','DDL',0,'7.0','Dirección IP'),
(2,'TSVECTOR','DATA_TYPE','DDL',0,'8.3','Búsqueda full-text'),
-- Joins
(2,'JOIN','CLAUSE','DML',1,'7.0',NULL),
(2,'INNER','MODIFIER','DML',0,'7.0',NULL),
(2,'LEFT','MODIFIER','DML',0,'7.0',NULL),
(2,'RIGHT','MODIFIER','DML',0,'7.0',NULL),
(2,'OUTER','MODIFIER','DML',0,'7.0',NULL),
(2,'CROSS','MODIFIER','DML',0,'7.0',NULL),
(2,'FULL','MODIFIER','DML',0,'7.0','FULL OUTER JOIN'),
(2,'ON','CLAUSE','DML',1,'7.0',NULL),
(2,'AS','MODIFIER','DML',0,'7.0',NULL),
-- Cláusulas
(2,'ORDER','CLAUSE','DML',1,'7.0',NULL),
(2,'BY','CLAUSE','DML',1,'7.0',NULL),
(2,'GROUP','CLAUSE','DML',1,'7.0',NULL),
(2,'HAVING','CLAUSE','DML',1,'7.0',NULL),
(2,'DISTINCT','MODIFIER','DML',1,'7.0',NULL),
(2,'LIMIT','CLAUSE','DML',0,'7.0',NULL),
(2,'OFFSET','CLAUSE','DML',0,'7.0',NULL),
-- Operadores
(2,'AND','OPERATOR','DML',1,'7.0',NULL),
(2,'OR','OPERATOR','DML',1,'7.0',NULL),
(2,'IN','OPERATOR','DML',1,'7.0',NULL),
(2,'LIKE','OPERATOR','DML',1,'7.0',NULL),
(2,'BETWEEN','OPERATOR','DML',1,'7.0',NULL),
(2,'IS','OPERATOR','DML',1,'7.0',NULL),
(2,'ANY','OPERATOR','DML',1,'7.0',NULL),
(2,'ALL','OPERATOR','DML',1,'7.0',NULL),
(2,'CASE','RESERVED','DML',1,'7.0',NULL),
(2,'WHEN','CLAUSE','DML',1,'7.0',NULL),
(2,'THEN','CLAUSE','DML',1,'7.0',NULL),
(2,'ELSE','CLAUSE','DML',1,'7.0',NULL),
(2,'END','CLAUSE','DML',1,'7.0',NULL),
-- Agregado
(2,'COUNT','FUNCTION','AGGREGATE',0,'7.0',NULL),
(2,'SUM','FUNCTION','AGGREGATE',0,'7.0',NULL),
(2,'AVG','FUNCTION','AGGREGATE',0,'7.0',NULL),
(2,'MIN','FUNCTION','AGGREGATE',0,'7.0',NULL),
(2,'MAX','FUNCTION','AGGREGATE',0,'7.0',NULL),
(2,'STRING_AGG','FUNCTION','AGGREGATE',0,'9.0','Equivalente a GROUP_CONCAT de MySQL'),
(2,'ARRAY_AGG','FUNCTION','AGGREGATE',0,'8.4',NULL),
-- Window
(2,'ROW_NUMBER','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'RANK','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'DENSE_RANK','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'LEAD','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'LAG','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'FIRST_VALUE','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'LAST_VALUE','FUNCTION','WINDOW',0,'8.4',NULL),
(2,'OVER','CLAUSE','WINDOW',0,'8.4',NULL),
(2,'PARTITION','CLAUSE','WINDOW',0,'8.4',NULL),
(2,'WINDOW','CLAUSE','WINDOW',0,'9.0','Definición de ventana reutilizable'),
-- DDL especiales
(2,'CONCURRENTLY','MODIFIER','DDL',0,'9.2','CREATE INDEX CONCURRENTLY'),
(2,'MATERIALIZED','MODIFIER','DDL',0,'9.3','CREATE MATERIALIZED VIEW'),
(2,'UNLOGGED','MODIFIER','DDL',0,'9.1','Tabla sin WAL'),
(2,'GENERATED','CLAUSE','DDL',0,'12.0','Columnas generadas'),
(2,'ALWAYS','MODIFIER','DDL',0,'12.0',NULL),
(2,'INHERITS','CLAUSE','DDL',0,'7.0','Herencia de tablas'),
(2,'TABLESPACE','CLAUSE','DDL',0,'8.0',NULL),
-- TCL
(2,'BEGIN','RESERVED','TCL',1,'7.0',NULL),
(2,'COMMIT','RESERVED','TCL',1,'7.0',NULL),
(2,'ROLLBACK','RESERVED','TCL',1,'7.0',NULL),
(2,'SAVEPOINT','RESERVED','TCL',1,'7.0',NULL),
(2,'START','RESERVED','TCL',1,'7.0',NULL),
(2,'TRANSACTION','RESERVED','TCL',1,'7.0',NULL),
-- Funciones
(2,'NOW','FUNCTION','DATETIME',0,'7.0',NULL),
(2,'CURRENT_DATE','FUNCTION','DATETIME',0,'7.0',NULL),
(2,'CURRENT_TIME','FUNCTION','DATETIME',0,'7.0',NULL),
(2,'AGE','FUNCTION','DATETIME',0,'7.0',NULL),
(2,'EXTRACT','FUNCTION','DATETIME',0,'7.0',NULL),
(2,'DATE_TRUNC','FUNCTION','DATETIME',0,'7.0',NULL),
(2,'INTERVAL','DATA_TYPE','DATETIME',0,'7.0',NULL),
(2,'CONCAT','FUNCTION','STRING',0,'9.1',NULL),
(2,'LENGTH','FUNCTION','STRING',0,'7.0',NULL),
(2,'SUBSTRING','FUNCTION','STRING',0,'7.0',NULL),
(2,'UPPER','FUNCTION','STRING',0,'7.0',NULL),
(2,'LOWER','FUNCTION','STRING',0,'7.0',NULL),
(2,'TRIM','FUNCTION','STRING',0,'7.0',NULL),
(2,'REPLACE','FUNCTION','STRING',0,'7.0',NULL),
(2,'COALESCE','FUNCTION','DML',0,'7.0',NULL),
(2,'NULLIF','FUNCTION','DML',0,'7.0',NULL),
(2,'CAST','FUNCTION','DML',0,'7.0',NULL),
(2,'GENERATE_SERIES','FUNCTION','DML',0,'8.0','Genera serie de valores'),
(2,'GEN_RANDOM_UUID','FUNCTION','DML',0,'13.0','Genera UUID v4'),
(2,'EXPLAIN','RESERVED','DML',0,'7.0',NULL),
(2,'ANALYZE','RESERVED','DDL',0,'7.0',NULL),
(2,'VACUUM','RESERVED','DDL',0,'7.0',NULL);

-- =============================================================================
-- SECCIÓN 4: KEYWORDS — SQL SERVER (dialect_id=3)
-- =============================================================================
INSERT IGNORE INTO keyword (dialect_id, word, token_type, category, is_reserved, since_version, notes) VALUES
(3,'SELECT','RESERVED','DML',1,'7.0',NULL),
(3,'INSERT','RESERVED','DML',1,'7.0',NULL),
(3,'UPDATE','RESERVED','DML',1,'7.0',NULL),
(3,'DELETE','RESERVED','DML',1,'7.0',NULL),
(3,'FROM','CLAUSE','DML',1,'7.0',NULL),
(3,'WHERE','CLAUSE','DML',1,'7.0',NULL),
(3,'SET','CLAUSE','DML',1,'7.0',NULL),
(3,'INTO','CLAUSE','DML',1,'7.0',NULL),
(3,'VALUES','CLAUSE','DML',1,'7.0',NULL),
(3,'CREATE','RESERVED','DDL',1,'7.0',NULL),
(3,'TABLE','RESERVED','DDL',1,'7.0',NULL),
(3,'DROP','RESERVED','DDL',1,'7.0',NULL),
(3,'ALTER','RESERVED','DDL',1,'7.0',NULL),
(3,'ADD','CLAUSE','DDL',1,'7.0',NULL),
(3,'COLUMN','CLAUSE','DDL',1,'7.0',NULL),
(3,'INDEX','RESERVED','DDL',1,'7.0',NULL),
(3,'PRIMARY','RESERVED','DDL',1,'7.0',NULL),
(3,'KEY','RESERVED','DDL',1,'7.0',NULL),
(3,'FOREIGN','RESERVED','DDL',1,'7.0',NULL),
(3,'REFERENCES','RESERVED','DDL',1,'7.0',NULL),
(3,'UNIQUE','RESERVED','DDL',1,'7.0',NULL),
(3,'DEFAULT','CLAUSE','DDL',1,'7.0',NULL),
(3,'NOT','OPERATOR','DML',1,'7.0',NULL),
(3,'NULL','RESERVED','DML',1,'7.0',NULL),
(3,'CONSTRAINT','RESERVED','DDL',1,'7.0',NULL),
(3,'TRUNCATE','RESERVED','DDL',1,'2000',NULL),
(3,'IF','MODIFIER','DDL',1,'7.0',NULL),
(3,'EXISTS','MODIFIER','DDL',1,'7.0',NULL),
-- Exclusivos SQL Server
(3,'TOP','MODIFIER','DML',0,'7.0','Limita filas devueltas (equivalente a LIMIT)'),
(3,'NOLOCK','PRAGMA','DML',0,'7.0','Lectura sin bloqueo (dirty read)'),
(3,'WITH','CLAUSE','DML',0,'7.0','CTE o table hints'),
(3,'OUTPUT','CLAUSE','DML',0,'2005','Equivalente a RETURNING de PostgreSQL'),
(3,'MERGE','RESERVED','DML',0,'2008','INSERT + UPDATE + DELETE en una sentencia'),
(3,'MATCHED','CLAUSE','DML',0,'2008','WHEN MATCHED THEN UPDATE'),
(3,'APPLY','CLAUSE','DML',0,'2005','CROSS APPLY / OUTER APPLY'),
(3,'PIVOT','CLAUSE','DML',0,'2005',NULL),
(3,'UNPIVOT','CLAUSE','DML',0,'2005',NULL),
-- Tipos exclusivos SQL Server
(3,'NVARCHAR','DATA_TYPE','DDL',0,'7.0','VARCHAR Unicode'),
(3,'NCHAR','DATA_TYPE','DDL',0,'7.0','CHAR Unicode'),
(3,'NTEXT','DATA_TYPE','DDL',0,'7.0','TEXT Unicode (deprecado en 2012)'),
(3,'MONEY','DATA_TYPE','DDL',0,'7.0',NULL),
(3,'SMALLMONEY','DATA_TYPE','DDL',0,'7.0',NULL),
(3,'DATETIME2','DATA_TYPE','DDL',0,'2008','Más preciso que DATETIME'),
(3,'DATETIMEOFFSET','DATA_TYPE','DDL',0,'2008','Con zona horaria'),
(3,'UNIQUEIDENTIFIER','DATA_TYPE','DDL',0,'7.0','UUID'),
(3,'BIT','DATA_TYPE','DDL',0,'7.0','Booleano'),
(3,'VARBINARY','DATA_TYPE','DDL',0,'7.0',NULL),
(3,'IMAGE','DATA_TYPE','DDL',0,'7.0','Deprecado, usar VARBINARY(MAX)'),
(3,'XML','DATA_TYPE','DDL',0,'2005',NULL),
-- Funciones exclusivas
(3,'GETDATE','FUNCTION','DATETIME',0,'7.0','Equivalente a NOW()'),
(3,'GETUTCDATE','FUNCTION','DATETIME',0,'7.0',NULL),
(3,'DATEADD','FUNCTION','DATETIME',0,'7.0',NULL),
(3,'DATEDIFF','FUNCTION','DATETIME',0,'7.0',NULL),
(3,'FORMAT','FUNCTION','STRING',0,'2012',NULL),
(3,'ISNULL','FUNCTION','DML',0,'7.0','Equivalente a COALESCE de 2 args'),
(3,'COALESCE','FUNCTION','DML',0,'7.0',NULL),
(3,'CONVERT','FUNCTION','DML',0,'7.0',NULL),
(3,'TRY_CAST','FUNCTION','DML',0,'2012','CAST sin excepción'),
(3,'TRY_CONVERT','FUNCTION','DML',0,'2012',NULL),
(3,'NEWID','FUNCTION','DML',0,'7.0','Genera GUID'),
(3,'IDENTITY','MODIFIER','DDL',0,'7.0','Equivalente a AUTO_INCREMENT'),
(3,'ROWCOUNT','PRAGMA','DML',0,'7.0','SET ROWCOUNT n'),
(3,'NOCOUNT','PRAGMA','DML',0,'7.0','SET NOCOUNT ON'),
(3,'XACT_ABORT','PRAGMA','TCL',0,'7.0','Rollback automático en error'),
-- Joins
(3,'JOIN','CLAUSE','DML',1,'7.0',NULL),
(3,'INNER','MODIFIER','DML',0,'7.0',NULL),
(3,'LEFT','MODIFIER','DML',0,'7.0',NULL),
(3,'RIGHT','MODIFIER','DML',0,'7.0',NULL),
(3,'OUTER','MODIFIER','DML',0,'7.0',NULL),
(3,'CROSS','MODIFIER','DML',0,'7.0',NULL),
(3,'FULL','MODIFIER','DML',0,'7.0',NULL),
(3,'ON','CLAUSE','DML',1,'7.0',NULL),
(3,'AS','MODIFIER','DML',0,'7.0',NULL),
-- Cláusulas
(3,'ORDER','CLAUSE','DML',1,'7.0',NULL),
(3,'BY','CLAUSE','DML',1,'7.0',NULL),
(3,'GROUP','CLAUSE','DML',1,'7.0',NULL),
(3,'HAVING','CLAUSE','DML',1,'7.0',NULL),
(3,'DISTINCT','MODIFIER','DML',1,'7.0',NULL),
(3,'FETCH','CLAUSE','DML',0,'2012','FETCH NEXT n ROWS ONLY'),
(3,'OFFSET','CLAUSE','DML',0,'2012',NULL),
(3,'ROWS','CLAUSE','DML',0,'2012',NULL),
(3,'ONLY','MODIFIER','DML',0,'2012',NULL),
-- Operadores
(3,'AND','OPERATOR','DML',1,'7.0',NULL),
(3,'OR','OPERATOR','DML',1,'7.0',NULL),
(3,'IN','OPERATOR','DML',1,'7.0',NULL),
(3,'LIKE','OPERATOR','DML',1,'7.0',NULL),
(3,'BETWEEN','OPERATOR','DML',1,'7.0',NULL),
(3,'IS','OPERATOR','DML',1,'7.0',NULL),
(3,'CASE','RESERVED','DML',1,'7.0',NULL),
(3,'WHEN','CLAUSE','DML',1,'7.0',NULL),
(3,'THEN','CLAUSE','DML',1,'7.0',NULL),
(3,'ELSE','CLAUSE','DML',1,'7.0',NULL),
(3,'END','CLAUSE','DML',1,'7.0',NULL),
-- Agregado
(3,'COUNT','FUNCTION','AGGREGATE',0,'7.0',NULL),
(3,'SUM','FUNCTION','AGGREGATE',0,'7.0',NULL),
(3,'AVG','FUNCTION','AGGREGATE',0,'7.0',NULL),
(3,'MIN','FUNCTION','AGGREGATE',0,'7.0',NULL),
(3,'MAX','FUNCTION','AGGREGATE',0,'7.0',NULL),
(3,'STRING_AGG','FUNCTION','AGGREGATE',0,'2017','Disponible desde SQL Server 2017'),
-- Window
(3,'ROW_NUMBER','FUNCTION','WINDOW',0,'2005',NULL),
(3,'RANK','FUNCTION','WINDOW',0,'2005',NULL),
(3,'DENSE_RANK','FUNCTION','WINDOW',0,'2005',NULL),
(3,'LEAD','FUNCTION','WINDOW',0,'2012',NULL),
(3,'LAG','FUNCTION','WINDOW',0,'2012',NULL),
(3,'OVER','CLAUSE','WINDOW',0,'2005',NULL),
(3,'PARTITION','CLAUSE','WINDOW',0,'2005',NULL),
(3,'ROLLUP','CLAUSE','AGGREGATE',0,'7.0','GROUP BY ROLLUP'),
(3,'CUBE','CLAUSE','AGGREGATE',0,'7.0',NULL),
(3,'GROUPING','FUNCTION','AGGREGATE',0,'7.0',NULL),
(3,'SETS','CLAUSE','AGGREGATE',0,'2008','GROUPING SETS'),
-- TCL
(3,'BEGIN','RESERVED','TCL',1,'7.0',NULL),
(3,'COMMIT','RESERVED','TCL',1,'7.0',NULL),
(3,'ROLLBACK','RESERVED','TCL',1,'7.0',NULL),
(3,'SAVEPOINT','RESERVED','TCL',1,'7.0',NULL),
(3,'TRANSACTION','RESERVED','TCL',1,'7.0',NULL),
(3,'EXPLAIN','RESERVED','DML',0,'2005','En SS es SET SHOWPLAN_XML');

-- =============================================================================
-- SECCIÓN 4: KEYWORDS — MONGODB (dialect_id=4)
-- =============================================================================
INSERT IGNORE INTO keyword (dialect_id, word, token_type, category, is_reserved, since_version, notes) VALUES
(4,'SELECT','RESERVED','DML',1,'4.0','Mapea a find() o aggregate()'),
(4,'FROM','CLAUSE','DML',1,'4.0','Nombre de colección'),
(4,'WHERE','CLAUSE','DML',1,'4.0','Mapea a filtro de find()'),
(4,'INSERT','RESERVED','DML',1,'4.0','Mapea a insertOne/insertMany'),
(4,'INTO','CLAUSE','DML',1,'4.0',NULL),
(4,'VALUES','CLAUSE','DML',1,'4.0',NULL),
(4,'DELETE','RESERVED','DML',1,'4.0','Mapea a deleteOne/deleteMany'),
(4,'UPDATE','RESERVED','DML',1,'4.0','Mapea a updateOne/updateMany'),
(4,'SET','CLAUSE','DML',1,'4.0','Mapea a $set'),
(4,'LIMIT','CLAUSE','DML',0,'4.0','Mapea a limit()'),
(4,'SKIP','CLAUSE','DML',0,'4.0','Equivalente a OFFSET'),
(4,'ORDER','CLAUSE','DML',0,'4.0',NULL),
(4,'BY','CLAUSE','DML',0,'4.0',NULL),
(4,'AND','OPERATOR','DML',1,'4.0','Mapea a $and'),
(4,'OR','OPERATOR','DML',1,'4.0','Mapea a $or'),
(4,'IN','OPERATOR','DML',0,'4.0','Mapea a $in'),
(4,'NOT','OPERATOR','DML',1,'4.0','Mapea a $not'),
-- Agregación MongoDB
(4,'AGGREGATE','RESERVED','DML',0,'2.2','Pipeline de agregación'),
(4,'MATCH','CLAUSE','DML',0,'2.2','Etapa $match'),
(4,'LOOKUP','CLAUSE','DML',0,'3.2','Equivalente a JOIN'),
(4,'UNWIND','CLAUSE','DML',0,'2.2','Descompone arrays'),
(4,'PROJECT','CLAUSE','DML',0,'2.2','Selecciona campos'),
(4,'GROUP','CLAUSE','DML',0,'2.2','Agrupación con acumuladores'),
(4,'SORT','CLAUSE','DML',0,'2.2','Ordenamiento'),
(4,'OUT','CLAUSE','DML',0,'2.6','Guarda resultado en colección'),
(4,'MERGE','CLAUSE','DML',0,'4.2','Merge en colección existente'),
(4,'FACET','CLAUSE','DML',0,'3.4','Multi-faceta'),
(4,'BUCKET','CLAUSE','DML',0,'3.4','Agrupación por rangos'),
(4,'SAMPLE','CLAUSE','DML',0,'3.2','Muestra aleatoria'),
(4,'COUNT','FUNCTION','AGGREGATE',0,'2.2','Mapea a $count'),
(4,'SUM','FUNCTION','AGGREGATE',0,'2.2','Mapea a $sum'),
(4,'AVG','FUNCTION','AGGREGATE',0,'2.2','Mapea a $avg'),
(4,'MIN','FUNCTION','AGGREGATE',0,'2.2','Mapea a $min'),
(4,'MAX','FUNCTION','AGGREGATE',0,'2.2','Mapea a $max'),
(4,'PUSH','FUNCTION','AGGREGATE',0,'2.2','Mapea a $push'),
(4,'ADDTOSET','FUNCTION','AGGREGATE',0,'2.2','Mapea a $addToSet'),
-- Tipos BSON
(4,'OBJECTID','DATA_TYPE','DDL',0,'1.0','Tipo _id por defecto'),
(4,'ISODATE','DATA_TYPE','DDL',0,'1.0','Fecha en formato ISO'),
(4,'NUMBERLONG','DATA_TYPE','DDL',0,'1.0','Entero 64-bit'),
(4,'NUMBERDECIMAL','DATA_TYPE','DDL',0,'3.4','Decimal 128-bit'),
(4,'BINDATA','DATA_TYPE','DDL',0,'1.0','Datos binarios BSON');

-- =============================================================================
-- SECCIÓN 5: MAPEO DE TIPOS DE DATO NATIVOS → ABSTRACTOS
-- =============================================================================

-- MySQL
INSERT IGNORE INTO data_type_mapping (dialect_id, native_type, abstract_type_id, max_length, requires_length, notes) VALUES
(1,'INT',      (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(1,'INTEGER',  (SELECT id FROM data_type WHERE name='INT'),      NULL,0,'Sinónimo de INT'),
(1,'BIGINT',   (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(1,'SMALLINT', (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(1,'TINYINT',  (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(1,'MEDIUMINT',(SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(1,'FLOAT',    (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(1,'DOUBLE',   (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(1,'DECIMAL',  (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(1,'NUMERIC',  (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(1,'VARCHAR',  (SELECT id FROM data_type WHERE name='VARCHAR'), 65535,1,'Requiere longitud máxima'),
(1,'CHAR',     (SELECT id FROM data_type WHERE name='VARCHAR'),  255,1,NULL),
(1,'TEXT',     (SELECT id FROM data_type WHERE name='TEXT'),     NULL,0,NULL),
(1,'MEDIUMTEXT',(SELECT id FROM data_type WHERE name='TEXT'),    NULL,0,NULL),
(1,'LONGTEXT', (SELECT id FROM data_type WHERE name='TEXT'),     NULL,0,NULL),
(1,'TINYTEXT', (SELECT id FROM data_type WHERE name='TEXT'),     NULL,0,NULL),
(1,'BOOLEAN',  (SELECT id FROM data_type WHERE name='BOOLEAN'),  NULL,0,NULL),
(1,'BOOL',     (SELECT id FROM data_type WHERE name='BOOLEAN'),  NULL,0,'Sinónimo de BOOLEAN'),
(1,'DATETIME', (SELECT id FROM data_type WHERE name='DATETIME'), NULL,0,NULL),
(1,'TIMESTAMP',(SELECT id FROM data_type WHERE name='DATETIME'), NULL,0,NULL),
(1,'DATE',     (SELECT id FROM data_type WHERE name='DATE'),     NULL,0,NULL),
(1,'TIME',     (SELECT id FROM data_type WHERE name='TIME'),     NULL,0,NULL),
(1,'BLOB',     (SELECT id FROM data_type WHERE name='BLOB'),     NULL,0,NULL),
(1,'MEDIUMBLOB',(SELECT id FROM data_type WHERE name='BLOB'),    NULL,0,NULL),
(1,'LONGBLOB', (SELECT id FROM data_type WHERE name='BLOB'),     NULL,0,NULL),
(1,'JSON',     (SELECT id FROM data_type WHERE name='JSON'),     NULL,0,'MySQL 5.7+'),
(1,'ENUM',     (SELECT id FROM data_type WHERE name='VARCHAR'),  NULL,0,NULL);

-- PostgreSQL
INSERT IGNORE INTO data_type_mapping (dialect_id, native_type, abstract_type_id, max_length, requires_length, notes) VALUES
(2,'INTEGER',  (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'INT',      (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'INT4',     (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'BIGINT',   (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'INT8',     (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'SMALLINT', (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'INT2',     (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'SERIAL',   (SELECT id FROM data_type WHERE name='INT'),      NULL,0,'Auto-incrementable'),
(2,'BIGSERIAL',(SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(2,'SMALLSERIAL',(SELECT id FROM data_type WHERE name='INT'),    NULL,0,NULL),
(2,'REAL',     (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(2,'FLOAT4',   (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(2,'DOUBLE PRECISION',(SELECT id FROM data_type WHERE name='FLOAT'),NULL,0,NULL),
(2,'FLOAT8',   (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(2,'NUMERIC',  (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(2,'DECIMAL',  (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(2,'VARCHAR',  (SELECT id FROM data_type WHERE name='VARCHAR'),  NULL,0,NULL),
(2,'CHARACTER VARYING',(SELECT id FROM data_type WHERE name='VARCHAR'),NULL,0,NULL),
(2,'CHAR',     (SELECT id FROM data_type WHERE name='VARCHAR'),  NULL,0,NULL),
(2,'TEXT',     (SELECT id FROM data_type WHERE name='TEXT'),     NULL,0,NULL),
(2,'BOOLEAN',  (SELECT id FROM data_type WHERE name='BOOLEAN'),  NULL,0,NULL),
(2,'BOOL',     (SELECT id FROM data_type WHERE name='BOOLEAN'),  NULL,0,NULL),
(2,'TIMESTAMP',(SELECT id FROM data_type WHERE name='DATETIME'), NULL,0,NULL),
(2,'TIMESTAMPTZ',(SELECT id FROM data_type WHERE name='DATETIME'),NULL,0,'Con zona horaria'),
(2,'DATE',     (SELECT id FROM data_type WHERE name='DATE'),     NULL,0,NULL),
(2,'TIME',     (SELECT id FROM data_type WHERE name='TIME'),     NULL,0,NULL),
(2,'BYTEA',    (SELECT id FROM data_type WHERE name='BLOB'),     NULL,0,NULL),
(2,'JSON',     (SELECT id FROM data_type WHERE name='JSON'),     NULL,0,NULL),
(2,'JSONB',    (SELECT id FROM data_type WHERE name='JSON'),     NULL,0,'JSON binario indexable'),
(2,'UUID',     (SELECT id FROM data_type WHERE name='UUID'),     NULL,0,NULL),
(2,'ARRAY',    (SELECT id FROM data_type WHERE name='ARRAY'),    NULL,0,NULL);

-- SQL Server
INSERT IGNORE INTO data_type_mapping (dialect_id, native_type, abstract_type_id, max_length, requires_length, notes) VALUES
(3,'INT',      (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(3,'BIGINT',   (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(3,'SMALLINT', (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(3,'TINYINT',  (SELECT id FROM data_type WHERE name='INT'),      NULL,0,NULL),
(3,'FLOAT',    (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(3,'REAL',     (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(3,'DECIMAL',  (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(3,'NUMERIC',  (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(3,'MONEY',    (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,NULL),
(3,'SMALLMONEY',(SELECT id FROM data_type WHERE name='FLOAT'),   NULL,0,NULL),
(3,'VARCHAR',  (SELECT id FROM data_type WHERE name='VARCHAR'),  8000,1,NULL),
(3,'NVARCHAR', (SELECT id FROM data_type WHERE name='VARCHAR'),  4000,1,'Unicode'),
(3,'CHAR',     (SELECT id FROM data_type WHERE name='VARCHAR'),  8000,1,NULL),
(3,'NCHAR',    (SELECT id FROM data_type WHERE name='VARCHAR'),  4000,1,NULL),
(3,'TEXT',     (SELECT id FROM data_type WHERE name='TEXT'),     NULL,0,'Deprecado'),
(3,'NTEXT',    (SELECT id FROM data_type WHERE name='TEXT'),     NULL,0,'Deprecado'),
(3,'BIT',      (SELECT id FROM data_type WHERE name='BOOLEAN'),  NULL,0,NULL),
(3,'DATETIME', (SELECT id FROM data_type WHERE name='DATETIME'), NULL,0,NULL),
(3,'DATETIME2',(SELECT id FROM data_type WHERE name='DATETIME'), NULL,0,'Más preciso'),
(3,'SMALLDATETIME',(SELECT id FROM data_type WHERE name='DATETIME'),NULL,0,NULL),
(3,'DATE',     (SELECT id FROM data_type WHERE name='DATE'),     NULL,0,NULL),
(3,'TIME',     (SELECT id FROM data_type WHERE name='TIME'),     NULL,0,NULL),
(3,'VARBINARY',(SELECT id FROM data_type WHERE name='BLOB'),     NULL,0,NULL),
(3,'IMAGE',    (SELECT id FROM data_type WHERE name='BLOB'),     NULL,0,'Deprecado'),
(3,'UNIQUEIDENTIFIER',(SELECT id FROM data_type WHERE name='UUID'),NULL,0,NULL),
(3,'XML',      (SELECT id FROM data_type WHERE name='JSON'),     NULL,0,NULL);

-- MongoDB
INSERT IGNORE INTO data_type_mapping (dialect_id, native_type, abstract_type_id, max_length, requires_length, notes) VALUES
(4,'String',    (SELECT id FROM data_type WHERE name='VARCHAR'),  NULL,0,'BSON String'),
(4,'Int32',     (SELECT id FROM data_type WHERE name='INT'),      NULL,0,'BSON Int32'),
(4,'Int64',     (SELECT id FROM data_type WHERE name='INT'),      NULL,0,'BSON Int64 / NumberLong'),
(4,'Double',    (SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,'BSON Double'),
(4,'Decimal128',(SELECT id FROM data_type WHERE name='FLOAT'),    NULL,0,'BSON Decimal128'),
(4,'Boolean',   (SELECT id FROM data_type WHERE name='BOOLEAN'),  NULL,0,NULL),
(4,'Date',      (SELECT id FROM data_type WHERE name='DATETIME'), NULL,0,'BSON Date'),
(4,'BinData',   (SELECT id FROM data_type WHERE name='BLOB'),     NULL,0,NULL),
(4,'ObjectId',  (SELECT id FROM data_type WHERE name='UUID'),     NULL,0,'_id por defecto'),
(4,'Array',     (SELECT id FROM data_type WHERE name='ARRAY'),    NULL,0,NULL),
(4,'Object',    (SELECT id FROM data_type WHERE name='JSON'),     NULL,0,'Documento embebido'),
(4,'Null',      (SELECT id FROM data_type WHERE name='UNKNOWN'),  NULL,0,NULL);

-- =============================================================================
-- SECCIÓN 6: SINTAXIS POR SENTENCIA Y DIALECTO
-- =============================================================================
INSERT IGNORE INTO statement_syntax (dialect_id, statement_id, supported, syntax_template, notes) VALUES
-- SELECT
(1,(SELECT id FROM sql_statement WHERE name='SELECT'),1,
 'SELECT [DISTINCT] {cols|*} FROM {table} [JOIN {table} ON {cond}] [WHERE {cond}] [GROUP BY {cols}] [HAVING {cond}] [ORDER BY {cols}] [LIMIT {n} [OFFSET {m}]]',
 'LIMIT es exclusivo de MySQL/MariaDB para paginación'),
(2,(SELECT id FROM sql_statement WHERE name='SELECT'),1,
 'SELECT [DISTINCT] {cols|*} FROM {table} [JOIN {table} ON {cond}] [WHERE {cond}] [GROUP BY {cols}] [HAVING {cond}] [ORDER BY {cols} [NULLS FIRST|LAST]] [LIMIT {n}] [FETCH NEXT {n} ROWS ONLY]',
 'Soporta RETURNING, CTE WITH, LATERAL, ILIKE'),
(3,(SELECT id FROM sql_statement WHERE name='SELECT'),1,
 'SELECT [TOP {n}] [DISTINCT] {cols|*} FROM {table} [WITH(NOLOCK)] [JOIN {table} ON {cond}] [WHERE {cond}] [GROUP BY {cols}] [HAVING {cond}] [ORDER BY {cols}] [OFFSET {n} ROWS FETCH NEXT {m} ROWS ONLY]',
 'Usa TOP en lugar de LIMIT'),
(4,(SELECT id FROM sql_statement WHERE name='SELECT'),1,
 'db.{coleccion}.find({filtro}, {proyeccion}).limit({n}).skip({m}).sort({campo}: 1|-1)}\n\n  SQL alternativo: SELECT {cols|*} FROM {coleccion} [WHERE {cond}] [ORDER BY {campo}] [LIMIT {n}] [SKIP {m}]',
 'Modo nativo: db.coleccion.find({ edad: {$gt: 18} }, { nombre: 1 }).limit(10).skip(0)'),
-- INSERT
(1,(SELECT id FROM sql_statement WHERE name='INSERT'),1,
 'INSERT INTO {table} [({cols})] VALUES ({vals}) [, ({vals})...] [ON DUPLICATE KEY UPDATE {col}={val}]',
 'Soporta INSERT múltiple y ON DUPLICATE KEY'),
(2,(SELECT id FROM sql_statement WHERE name='INSERT'),1,
 'INSERT INTO {table} [({cols})] VALUES ({vals}) [ON CONFLICT ({col}) DO {UPDATE SET ... | NOTHING}] [RETURNING {cols|*}]',
 'Upsert nativo con ON CONFLICT'),
(3,(SELECT id FROM sql_statement WHERE name='INSERT'),1,
 'INSERT INTO {table} [({cols})] VALUES ({vals}) [OUTPUT INSERTED.*]',
 'OUTPUT equivale a RETURNING'),
(4,(SELECT id FROM sql_statement WHERE name='INSERT'),1,
 'db.{coleccion}.insertOne({ documento })\ndb.{coleccion}.insertMany([{ doc1 }, { doc2 }])\n\n  SQL alternativo: INSERT INTO {coleccion} VALUES ({json_doc})',
 'Modo nativo: db.usuarios.insertOne({ nombre: "Juan", edad: 30 })'),
-- UPDATE
(1,(SELECT id FROM sql_statement WHERE name='UPDATE'),1,
 'UPDATE {table} SET {col}={val} [, {col}={val}...] [WHERE {cond}] [ORDER BY {col}] [LIMIT {n}]',
 'MySQL permite LIMIT y ORDER BY en UPDATE'),
(2,(SELECT id FROM sql_statement WHERE name='UPDATE'),1,
 'UPDATE {table} SET {col}={val} [FROM {otra_tabla}] [WHERE {cond}] [RETURNING {cols|*}]',
 'FROM permite unir otra tabla; RETURNING devuelve filas afectadas'),
(3,(SELECT id FROM sql_statement WHERE name='UPDATE'),1,
 'UPDATE {table} SET {col}={val} [OUTPUT DELETED.*, INSERTED.*] [FROM {join}] [WHERE {cond}]',
 'OUTPUT captura valores antes y después'),
(4,(SELECT id FROM sql_statement WHERE name='UPDATE'),1,
 'db.{coleccion}.updateOne({ filtro }, { $set: { campo: valor } })\ndb.{coleccion}.updateMany({ filtro }, { $set: { campo: valor } })\n\n  SQL alternativo: UPDATE {coleccion} SET {campo}={val} [WHERE {cond}]',
 'Modo nativo: db.usuarios.updateOne({ edad: {$gt: 30} }, { $set: { activo: false } })'),
-- DELETE
(1,(SELECT id FROM sql_statement WHERE name='DELETE'),1,
 'DELETE FROM {table} [WHERE {cond}] [ORDER BY {col}] [LIMIT {n}]',NULL),
(2,(SELECT id FROM sql_statement WHERE name='DELETE'),1,
 'DELETE FROM {table} [USING {otra_tabla}] [WHERE {cond}] [RETURNING {cols|*}]',
 'USING permite filtrar con join'),
(3,(SELECT id FROM sql_statement WHERE name='DELETE'),1,
 'DELETE [TOP ({n})] FROM {table} [OUTPUT DELETED.*] [WHERE {cond}]',NULL),
(4,(SELECT id FROM sql_statement WHERE name='DELETE'),1,
 'db.{coleccion}.deleteOne({ filtro })\ndb.{coleccion}.deleteMany({ filtro })\n\n  SQL alternativo: DELETE FROM {coleccion} [WHERE {cond}]',
 'Modo nativo: db.usuarios.deleteMany({ activo: false })'),
-- CREATE TABLE
(1,(SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),1,
 'CREATE TABLE [IF NOT EXISTS] {table} ({col} {tipo} [NOT NULL] [DEFAULT {val}] [AUTO_INCREMENT] [PRIMARY KEY], ...) [ENGINE=InnoDB] [DEFAULT CHARSET=utf8mb4]',NULL),
(2,(SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),1,
 'CREATE [UNLOGGED] TABLE [IF NOT EXISTS] {table} ({col} {tipo} [NOT NULL] [DEFAULT {val}] [GENERATED ALWAYS AS ({expr}) STORED], ...) [INHERITS ({padre})]',
 'UNLOGGED = sin WAL. Soporta herencia de tablas.'),
(3,(SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),1,
 'CREATE TABLE [IF NOT EXISTS] {table} ({col} {tipo} [NOT NULL] [DEFAULT {val}] [IDENTITY(1,1)] [PRIMARY KEY], ...)',
 'IDENTITY equivale a AUTO_INCREMENT'),
(4,(SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),0,NULL,
 'MongoDB no tiene DDL: las colecciones se crean implícitamente al insertar'),
-- ALTER TABLE
(1,(SELECT id FROM sql_statement WHERE name='ALTER_TABLE'),1,
 'ALTER TABLE {table} {ADD COLUMN {col} {tipo} | DROP COLUMN {col} | MODIFY COLUMN {col} {tipo} | RENAME COLUMN {old} TO {new}}',NULL),
(2,(SELECT id FROM sql_statement WHERE name='ALTER_TABLE'),1,
 'ALTER TABLE {table} {ADD COLUMN {col} {tipo} | DROP COLUMN {col} | ALTER COLUMN {col} TYPE {tipo} | RENAME COLUMN {old} TO {new}}',NULL),
(3,(SELECT id FROM sql_statement WHERE name='ALTER_TABLE'),1,
 'ALTER TABLE {table} {ADD {col} {tipo} | DROP COLUMN {col} | ALTER COLUMN {col} {tipo}}',NULL),
(4,(SELECT id FROM sql_statement WHERE name='ALTER_TABLE'),0,NULL,
 'MongoDB no soporta ALTER TABLE; los schemas son flexibles'),
-- DROP TABLE
(1,(SELECT id FROM sql_statement WHERE name='DROP_TABLE'),1,
 'DROP TABLE [IF EXISTS] {table} [, {table}...]',NULL),
(2,(SELECT id FROM sql_statement WHERE name='DROP_TABLE'),1,
 'DROP TABLE [IF EXISTS] {table} [CASCADE | RESTRICT]',
 'CASCADE elimina objetos dependientes automáticamente'),
(3,(SELECT id FROM sql_statement WHERE name='DROP_TABLE'),1,
 'DROP TABLE [IF EXISTS] {table}',NULL),
(4,(SELECT id FROM sql_statement WHERE name='DROP_TABLE'),0,NULL,
 'MongoDB usa db.collection.drop()'),
-- TRUNCATE
(1,(SELECT id FROM sql_statement WHERE name='TRUNCATE'),1,
 'TRUNCATE [TABLE] {table}','No se puede revertir con ROLLBACK en MySQL'),
(2,(SELECT id FROM sql_statement WHERE name='TRUNCATE'),1,
 'TRUNCATE [TABLE] {table} [RESTART IDENTITY] [CASCADE]',
 'RESTART IDENTITY resetea secuencias'),
(3,(SELECT id FROM sql_statement WHERE name='TRUNCATE'),1,
 'TRUNCATE TABLE {table}',NULL),
(4,(SELECT id FROM sql_statement WHERE name='TRUNCATE'),0,NULL,
 'MongoDB usa deleteMany({}) o drop() + recrear colección');

-- =============================================================================
-- SECCIÓN 7: KEYWORDS POR SENTENCIA
-- =============================================================================
INSERT IGNORE INTO statement_keyword (statement_id, keyword_id, role, position_hint, notes) VALUES
-- SELECT / MySQL
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='SELECT'),'REQUIRED','START',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='FROM'),'REQUIRED','AFTER_COLS',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='WHERE'),'OPTIONAL','AFTER_TABLE',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='DISTINCT'),'OPTIONAL','AFTER_SELECT',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='GROUP'),'OPTIONAL','AFTER_WHERE',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='HAVING'),'OPTIONAL','AFTER_GROUP',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='ORDER'),'OPTIONAL','AFTER_HAVING',NULL),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='LIMIT'),'OPTIONAL','END','Exclusivo MySQL'),
((SELECT id FROM sql_statement WHERE name='SELECT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='JOIN'),'OPTIONAL','AFTER_TABLE',NULL),
-- INSERT / MySQL
((SELECT id FROM sql_statement WHERE name='INSERT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='INSERT'),'REQUIRED','START',NULL),
((SELECT id FROM sql_statement WHERE name='INSERT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='INTO'),'REQUIRED','AFTER_INSERT',NULL),
((SELECT id FROM sql_statement WHERE name='INSERT'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='VALUES'),'OPTIONAL','AFTER_COLS','Opcional si se usa INSERT ... SELECT'),
-- UPDATE / MySQL
((SELECT id FROM sql_statement WHERE name='UPDATE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='UPDATE'),'REQUIRED','START',NULL),
((SELECT id FROM sql_statement WHERE name='UPDATE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='SET'),'REQUIRED','AFTER_TABLE',NULL),
((SELECT id FROM sql_statement WHERE name='UPDATE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='WHERE'),'OPTIONAL','AFTER_SET','Sin WHERE actualiza toda la tabla'),
((SELECT id FROM sql_statement WHERE name='UPDATE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='LIMIT'),'OPTIONAL','END','Limita filas actualizadas'),
-- DELETE / MySQL
((SELECT id FROM sql_statement WHERE name='DELETE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='DELETE'),'REQUIRED','START',NULL),
((SELECT id FROM sql_statement WHERE name='DELETE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='FROM'),'REQUIRED','AFTER_DELETE',NULL),
((SELECT id FROM sql_statement WHERE name='DELETE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='WHERE'),'OPTIONAL','AFTER_TABLE','Sin WHERE elimina toda la tabla'),
-- CREATE TABLE / MySQL
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='CREATE'),'REQUIRED','START',NULL),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='TABLE'),'REQUIRED','AFTER_CREATE',NULL),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='IF'),'OPTIONAL','AFTER_TABLE',NULL),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='EXISTS'),'OPTIONAL','AFTER_IF',NULL),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='PRIMARY'),'OPTIONAL','INSIDE_DEF',NULL),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='FOREIGN'),'OPTIONAL','INSIDE_DEF',NULL),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='AUTO_INCREMENT'),'OPTIONAL','INSIDE_COL','Exclusivo MySQL'),
((SELECT id FROM sql_statement WHERE name='CREATE_TABLE'),(SELECT id FROM keyword WHERE dialect_id=1 AND word='ENGINE'),'OPTIONAL','END','Exclusivo MySQL');
